### ISSUE TITLE
[Bugs] 기록 페이지 Failed to construct 'Intersection': rootMargin must be specified in pixels or percent.

### ISSUE THREAD

**Issue by IceCream0910** [fecapark/time-timer#3]
### 재현 경로
[https://timer.fecapark.com/records](https://timer.fecapark.com/records)

### 원인
해당 페이지에서 개발자 도구 콘솔 확인 시 아래와 같은 오류 메시지 확인이 가능합니다.
`Failed to construct 'IntersectionObserver': rootMargin must be specified in pixels or percent.`

### 수정
해당 오류는 IntersectionObserver의 option 중 rootMargin 지정 시 0에 단위를 적어주지 않아서 발생한 것으로 추정됩니다.
아래는 관련 링크입니다.
[https://github.com/w3c/IntersectionObserver/issues/126](https://github.com/w3c/IntersectionObserver/issues/126)
[https://velog.io/@nemo/IntersectionObserver-options-error](https://velog.io/@nemo/IntersectionObserver-options-error)

---
따라서 아래와 같이 4개의 컴포넌트에서 rootMargin 옵션이 `0`으로 작성된 부분을 `0px`로 단위를 밝혀 수정해야 할 것으로 보입니다.

`components/pages/records/RecordLogs/SameDayContainer/SameDayContainer.tsx`
`components/pages/records/RecordOverview/contents/Graph/Graph.tsx`
`components/pages/records/RecordOverview/contents/Behavior/Behavior.tsx`
`components/pages/records/RecordOverview/contents/TotalTime/TotalTime.tsx`

```
const { collide, scrolled } = useViewportCollision({
    ...
    rootMargin: "0px 0px -80px 0px",
  });
```

**Comment by fecapark** [comment]
@IceCream0910 감사합니다! 
해당 이슈 수정 완료 및 main 브랜치에 push 완료했습니다!
